### ISSUE TITLE
StackNavigator deprecated warning

### ISSUE THREAD

**Issue by wolverineks** [teamplanes/expobook#8]
```
The StackNavigator function name is deprecated, please use createStackNavigator instead
```
this fixes it, but I'm not sure where this file comes from
```js
// __expobook__/index.js
- import  { StackNavigator }  from 'react-navigation';
+ import  { createStackNavigator }  from 'react-navigation';
```

**Comment by kirkness** [comment]
Thanks @wolverineks, ill try to get a fix for this released by the end of the week.

**Comment by arnoldsandoval** [comment]
Looks like this can be closed?

**Comment by jesconstantine** [comment]
@arnoldsandoval Did the above commit make it into a release? I've just installed expobook today (using the branch created in https://github.com/teamplanes/expobook/pull/10 to resolve that build error) and I'm still seeing the warning.  Thanks!

**Comment by ma-pe** [comment]
With the new `react-navigation` version (3.0.0) this is not only a deprecated warning anymore. StackNavigator is not available anymore. With the package.json using the newest react-navigation (`"react-navigation": "*"`) expobook won't start anymore :(

Could you please merge the branch into master? Thanks! :)

**Comment by kirkness** [comment]
Hello! Ill get this done today.

**Comment by ma-pe** [comment]
https://github.com/teamplanes/expobook/pull/12
